# Generated by Django 3.0.4 on 2020-03-16 21:22

from django.db import migrations, models
import proxy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABCAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_id', models.UUIDField()),
                ('forward_url', models.TextField()),
                ('api_key', models.CharField(default=proxy.models.create_secret, max_length=255)),
            ],
            options={
                'verbose_name': 'ABC Account',
                'verbose_name_plural': 'ABC Accounts',
            },
        ),
    ]
